// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQoX63F8qx9kLNjIX_GFfCsWtRWdNOxlQ',
    appId: '1:966119648474:web:b041145f5ef6f2596389e3',
    messagingSenderId: '966119648474',
    projectId: 'quran-app-8e802',
    authDomain: 'quran-app-8e802.firebaseapp.com',
    storageBucket: 'quran-app-8e802.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGLjX--fU-JB9WQD33ztq0X3yHBXCRGD0',
    appId: '1:966119648474:android:d52f14406993f3c16389e3',
    messagingSenderId: '966119648474',
    projectId: 'quran-app-8e802',
    storageBucket: 'quran-app-8e802.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_dapcCALo9TMUQ0EjuQH_6YkC6zOjmUU',
    appId: '1:966119648474:ios:de25f4c5f297b06b6389e3',
    messagingSenderId: '966119648474',
    projectId: 'quran-app-8e802',
    storageBucket: 'quran-app-8e802.appspot.com',
    iosClientId: '966119648474-046r1412ajqok3doer92qf6un1f1mora.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_dapcCALo9TMUQ0EjuQH_6YkC6zOjmUU',
    appId: '1:966119648474:ios:68f50ae6173994126389e3',
    messagingSenderId: '966119648474',
    projectId: 'quran-app-8e802',
    storageBucket: 'quran-app-8e802.appspot.com',
    iosClientId: '966119648474-1u8jnfvcudu624nnus2fqimg0m7em4ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranApp.RunnerTests',
  );
}
